# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-26 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
